### ISSUE TITLE
No such table: messages (Edit: Support for WhatsApp databases with "message" table)

### ISSUE THREAD

**Issue by Takepy** [KnugiHK/Whatsapp-Chat-Exporter#9] opened 2022-02-18 13:40 UTC
When running the script I get following error message

```
Gathering contacts...(97)
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 147, in main
    messages(db, data)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 88, in messages
    c.execute("""SELECT count() FROM messages""")
sqlite3.OperationalError: no such table: messages
```
My database doesn't contain the table `messages`, I only have one called `message` which contains the data but the schema of the table looks different from what it's supposed to look like. 
![2022-02-14_22-28-04](https://user-images.githubusercontent.com/18618866/154693140-b1f9ab0d-5039-4f61-9e5e-9291a9575e9c.png)
What could be the issue here?

**Comment by Takepy** [comment] 2022-02-18 13:59
I'm using Android. 
WhatsApp versions that have been used are  2.22.3.77 and 2.22.5.7 (Beta)
2.22.3.77 was running on an emulator so that I could pull the /com.whatsapp/ directory. 
On the 2.22.5.7 version I used the previously pulled key to decrypt the db.

**Comment by KnugiHK** [comment] 2022-02-18 14:04
Is both versions and environments result in same database schema?

**Comment by Takepy** [comment] 2022-02-18 14:05
Yes, they both resulted in the same database schema

**Comment by KnugiHK** [comment] 2022-02-18 14:08
Interesting. I will try to reproduce it with 2.22.3.77 on emulator.

**Comment by Takepy** [comment] 2022-02-19 13:47
I installed WhatsApp on the emulator on the 9th of this month and then imported my chat history using the chat backup in WhatsApp. 
On my actual phone, WhatsApp has been installed like 6 months ago.

**Comment by KnugiHK** [comment] 2022-02-21 05:11
I have check some similar project and suspect that "message" table is a legacy table for storing messages. On your phone, is the WhatsApp conversation restored from old backup after installation?

**Comment by Takepy** [comment] 2022-02-21 12:49
I restored the WhatsApp conversations from Google Drive (doing weekly backups).
Never deleted my WhatsApp chat history though so the messages go all the way back to 2013

**Comment by KnugiHK** [comment] 2022-02-21 15:05
As far as I observed, it is possible that "message" was used in the early years of WhatsApp. Could you check if new installation without backup will result the same situation?

**Comment by Takepy** [comment] 2022-02-21 15:11
I'll give it a try later and report back.

**Comment by Takepy** [comment] 2022-02-22 18:41
Sorry, it took a little bit longer until I had time to try it out. 
Setup a new emulator, installed WhatsApp and didn't import my backup.
The table `messages` exists now.

So I'm guessing my backup is just too old for it to work then? :(

**Comment by KnugiHK** [comment] 2022-02-23 05:24
> Sorry, it took a little bit longer until I had time to try it out.

No problem!

> So I'm guessing my backup is just too old for it to work then? :(

I think so.
I would like to add support for older version. However, I don't have such database, hence, I am not able to do it. If you have time and you want the script to work with your database, you can take a look inside the database and fine tune the script.
Anyway, I will keep my eyes on the opportunity for supporting old databases. Thanks for your report!

**Comment by Unbrick** [comment] 2022-04-06 09:45
Hey everyone! I just stumbled upon the same issue with WhatsApp version 2.22.7.73 on Android on two different devices using two different phone numbers without restoring any backup.

I'll try to reinstall WhatsApp and try it again, but it seems like the database scheme is changing. The new messages table has the following schema:

```sql
CREATE TABLE message (
  _id INTEGER PRIMARY KEY AUTOINCREMENT, 
  chat_row_id INTEGER NOT NULL, from_me INTEGER NOT NULL, 
  key_id TEXT NOT NULL, sender_jid_row_id INTEGER, 
  status INTEGER, broadcast INTEGER, 
  recipient_count INTEGER, participant_hash TEXT, 
  origination_flags INTEGER, origin INTEGER, 
  timestamp INTEGER, received_timestamp INTEGER, 
  receipt_server_timestamp INTEGER, 
  message_type INTEGER, text_data TEXT, 
  starred INTEGER, lookup_tables INTEGER, 
  message_add_on_flags INTEGER, sort_id INTEGER NOT NULL DEFAULT 0
);
```

**Comment by KnugiHK** [comment] 2022-04-06 15:43
> I'll try to reinstall WhatsApp and try it again, but it seems like the database scheme is changing. The new messages table has the following schema:

I can produce the same result.

@Takepy As I can reproduce your situation now, I will work on supporting "message" table.

**Comment by KnugiHK** [comment] 2022-04-06 17:18
WhatsApp using "message" table spread different types of message to many other tables. Good chance for me to rewrite the project :)

**Comment by karanrajpal14** [comment] 2022-05-15 23:02
@Takepy were you able to find a way around this issue? Looks like I'm in the same boat, unfortunately and my whatsapp database is using the "legacy" format as well. I've got messages dating back all the way to 2014.

**Comment by get-trucked** [comment] 2022-07-18 08:19
@karanrajpal14 I came across the same issues as well, got a new phone and couldnt export the messages. Did you have any luck getting it to work?

I've started on a c# project to extract the messages which is working to extract and dump to text, just working on the html part now

**Comment by ulno** [comment] 2022-08-08 11:02
Has anyone made some progress here - it now seems as if it has to do with new versions of whatsapp? Or does it only affect people with a very long message history? I am very ready to back everything up and try moving to a full puppeteered whatsapp with mautrix-whatsapp, but things seem to still be shifting way too much.

@KnugiHK any way we can help?

**Comment by KnugiHK** [comment] 2022-08-09 02:27
> Has anyone made some progress here - it now seems as if it has to do with new versions of whatsapp? Or does it only affect people with a very long message history? I am very ready to back everything up and try moving to a full puppeteered whatsapp with mautrix-whatsapp, but things seem to still be shifting way too much.
> 
> @KnugiHK any way we can help?

The hardest part of this project is to understand the structure of the WhatsApp database. Any clues on the structure and pull requests are welcome.

**Comment by ulno** [comment] 2022-08-09 06:24
I played with it a bit yesterday and replaced the main query in extract.py with this:
```
SELECT message.sender_jid_row_id as key_remote_jid,
                        message._id,
                        message.from_me as key_from_me,
                        message.timestamp,
                        message.text_data as data,
                        message.status,
                        message_future.version as edit_version,
                        message_thumbnail.thumbnail as thumb_image,
                        message_media.file_path as remote_resource,
                        message_media.mime_type as media_wa_type,
                        message_location.latitude,
                        message_location.longitude,
                        message_quoted.key_id as quoted,
                        message.key_id,
                        message_quoted.text_data as quoted_data,
                        message_media.media_caption
                 FROM message
                    LEFT JOIN message_quoted
                        ON message_quoted.message_row_id = message._id
                    LEFT JOIN message_location
                        ON message_location.message_row_id = message._id
                    LEFT JOIN message_media
                        ON message_media.message_row_id = message._id
                    LEFT JOIN message_thumbnail
                        ON message_thumbnail.message_row_id = message._id
                    LEFT JOIN message_future
                        ON message_future.message_row_id = message._id
                    WHERE key_remote_jid <> '-1';
```

That brings me past the missing messages db, but will clash in extract.py:240 trying to match the remote id to something in the big data dictionary. So, I assume me trying to replace key_remote_jid with sender_jid_row_id might go into the right direction, but might need some more joints to actually turn things into a phone number.

There are also a messages_view and a chats_view now that seem to match some more tables with each other. Did anybody else figure some dependencies based on their connections out?

**Comment by KnugiHK** [comment] 2022-08-09 17:24
> I played with it a bit yesterday and replaced the main query in extract.py with this:
> 
> ```
> SELECT message.sender_jid_row_id as key_remote_jid,
>                         message._id,
>                         message.from_me as key_from_me,
>                         message.timestamp,
>                         message.text_data as data,
>                         message.status,
>                         message_future.version as edit_version,
>                         message_thumbnail.thumbnail as thumb_image,
>                         message_media.file_path as remote_resource,
>                         message_media.mime_type as media_wa_type,
>                         message_location.latitude,
>                         message_location.longitude,
>                         message_quoted.key_id as quoted,
>                         message.key_id,
>                         message_quoted.text_data as quoted_data,
>                         message_media.media_caption
>                  FROM message
>                     LEFT JOIN message_quoted
>                         ON message_quoted.message_row_id = message._id
>                     LEFT JOIN message_location
>                         ON message_location.message_row_id = message._id
>                     LEFT JOIN message_media
>                         ON message_media.message_row_id = message._id
>                     LEFT JOIN message_thumbnail
>                         ON message_thumbnail.message_row_id = message._id
>                     LEFT JOIN message_future
>                         ON message_future.message_row_id = message._id
>                     WHERE key_remote_jid <> '-1';
> ```
> 
> That brings me past the missing messages table, but will clash in extract.py:240 trying to match the remote id to something in the big data dictionary. So, I assume me trying to replace key_remote_jid with sender_jid_row_id might go into the right direction, but might need some more joints to actually turn things into a phone number.
> 
> There are also a messages_view and a chats_view now that seem to match some more tables with each other. Did anybody else figure some dependencies based on their connections out?

I will have a look at the clash later.

**Comment by stevanuscolonne** [comment] 2022-09-09 17:18
> I am curious about how WhatsApp decides which table to store messages 🤨. Is "message" a legacy table? Or "messages" is the legacy one?

"messages" is the legacy one, please read https://thebinaryhick.blog/2022/06/09/new-msgstore-who-dis-a-look-at-an-updated-whatsapp-on-android/

**Comment by stevanuscolonne** [comment] 2022-09-09 17:23
> I played with it a bit yesterday and replaced the main query in extract.py with this:
> ```
> SELECT message.sender_jid_row_id as key_remote_jid,
>                         message._id,
>                         message.from_me as key_from_me,
>                         message.timestamp,
>                         message.text_data as data,
>                         message.status,
>                         message_future.version as edit_version,
>                         message_thumbnail.thumbnail as thumb_image,
>                         message_media.file_path as remote_resource,
>                         message_media.mime_type as media_wa_type,
>                         message_location.latitude,
>                         message_location.longitude,
>                         message_quoted.key_id as quoted,
>                         message.key_id,
>                         message_quoted.text_data as quoted_data,
>                         message_media.media_caption
>                  FROM message
>                     LEFT JOIN message_quoted
>                         ON message_quoted.message_row_id = message._id
>                     LEFT JOIN message_location
>                         ON message_location.message_row_id = message._id
>                     LEFT JOIN message_media
>                         ON message_media.message_row_id = message._id
>                     LEFT JOIN message_thumbnail
>                         ON message_thumbnail.message_row_id = message._id
>                     LEFT JOIN message_future
>                         ON message_future.message_row_id = message._id
>                     WHERE key_remote_jid <> '-1';
> ```
> 
> That brings me past the missing messages table, but will clash in extract.py:240 trying to match the remote id to something in the big data dictionary. So, I assume me trying to replace key_remote_jid with sender_jid_row_id might go into the right direction, but might need some more joints to actually turn things into a phone number.
> 
> There are also a messages_view and a chats_view now that seem to match some more tables with each other. Did anybody else figure some dependencies based on their connections out?

key_remote_jid same with raw_string from table jid

**Comment by KnugiHK** [comment] 2022-11-08 08:35
> Are there any updates on this?

Not yet. Hopefully there will be updates on Dec.

**Comment by newdrkhckr** [comment] 2022-12-16 11:59
Are there any updates on ?

**Comment by newdrkhckr** [comment] 2022-12-16 18:56
Found a solution but i am not sure every aspect of project is working properly. 

First https://github.com/andreas-mausch/whatsapp-viewer/issues/151#issuecomment-1229244368 
I applied this solution this solition modified old msgstore.db.

After that  i still recieved errorS. So with SQLlite i add new tables to overcome error: no such table: ...
After adding couple tables, code is working now.  And able to output a result.

But as i said i cannot confirm that every aspect of project is working properly.

**Comment by KnugiHK** [comment] 2022-12-21 12:26
Hi everyone,
I am working on porting the code to the WhatsApp database with new schema. The main part is completed and there are some bugs need to be fixed.

**Comment by KnugiHK** [comment] 2022-12-21 13:50
I created a new branch called "[testing](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/tree/testing)" which support "message" table directly from wtsexporter command. Feel free to give it a try but please expect bugs from the branch. Bug reports are welcome and should be reported in this issue.

**Comment by Takepy** [comment] 2022-12-21 17:03
First of all, thank you for working on this. 
I just downloaded the branch and gave it a try. 
Unfortunately it didn't work for me. 

```
╰─ wtsexporter -a
Gathering contacts...(97)
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 174, in main
    messages(db, data)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 195, in messages
    c.execute("""SELECT count() FROM messages""")
sqlite3.OperationalError: no such table: messages
```

I made sure to uninstall the old version I had with `pip uninstall whatsapp-chat-exporter` and then installed the new one. 
Is there anything I'm missing?

**Comment by KnugiHK** [comment] 2022-12-22 13:25
> First of all, thank you for working on this. I just downloaded the branch and gave it a try. Unfortunately it didn't work for me.
> 
> ```
> ╰─ wtsexporter -a
> Gathering contacts...(97)
> Traceback (most recent call last):
>   File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\******\AppData\Local\Programs\Python\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
>   File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 174, in main
>     messages(db, data)
>   File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract.py", line 195, in messages
>     c.execute("""SELECT count() FROM messages""")
> sqlite3.OperationalError: no such table: messages
> ```
> 
> I made sure to uninstall the old version I had with `pip uninstall whatsapp-chat-exporter` and then installed the new one. Is there anything I'm missing?

Can you verify that the `__main__.py` file import extract_new `from Whatsapp_Chat_Exporter import extract_new as extract` instead of extract `from Whatsapp_Chat_Exporter import extract, extract_iphone`

**Comment by Takepy** [comment] 2022-12-22 17:03
`__main__.py` did not include `from Whatsapp_Chat_Exporter import extract_new as extract`.
Replaced the files in `\site-packages\Whatsapp_Chat_Exporter` manually with the ones from the branch now and ran the script again. 
Now being faced with this 
```
╰─ wtsexporter -a
Gathering contacts...(97)
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\Scripts\wtsexporter.exe\__main__.py", line 7, in <module>
  File "C:\Users\GLa******OS\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\__main__.py", line 184, in main
    messages(db, data)
  File "C:\Users\******\AppData\Local\Programs\Python\Python310\lib\site-packages\Whatsapp_Chat_Exporter\extract_new.py", line 206, in messages
    c.execute("""SELECT jid.raw_string as key_remote_jid,
sqlite3.OperationalError: no such column: message_media.media_caption
```

**Comment by KnugiHK** [comment] 2022-12-23 09:29
It should be fixed in the latest commit: https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/d3892a4e4f4f0b533107f871a23de22153cc879a.

**Comment by cbzittoun** [comment] 2022-12-27 14:34
The new branch worked on my side -- thanks a lot !
Although all medias are missing from the htmls (i tried both with and without the -e flag).
Thanks a lot for your work, your tool is great.

**Comment by velecto1** [comment] 2022-12-27 15:12
> The new branch worked on my side -- thanks a lot ! Although all medias are missing from the htmls (i tried both with and without the -e flag). Thanks a lot for your work, your tool is great.

Hello, @cbzittoun , I had the same problem with the media. Try to pass the parent directory of "Media" instead of the address to "Media" itself.

I still have three issues, though:

- All exported conversations start with "This message is not supported".
- The flag "-s" seems not to be working.
- I've realized that it would also be helpful for me to split the result into multiple HTML files 🙈.

**Comment by cbzittoun** [comment] 2022-12-27 15:54
I think I was pointing to no Media folder actually.
I was expecting the script to copy the files, not move them (although safer, it would be slower).

https://github.com/KnugiHK/Whatsapp-Chat-Exporter/blob/580eaddb24ee359433593776f1b6643e01d91979/Whatsapp_Chat_Exporter/extract.py#L531

Maybe is it worth an explicit warning that input files have been moved around?

**Comment by KnugiHK** [comment] 2022-12-28 15:22
@cbzittoun
> The new branch worked on my side -- thanks a lot ! Although all medias are missing from the htmls (i tried both with and without the -e flag). Thanks a lot for your work, your tool is great.

Actually, embedding media to the HTML file (-e option) is removed and was presented in the very early version. It is planned to have embedding again. Media should be located under `WhatsApp` folder (i.e., `WhatsApp/Media`). If your current working directory has the folder named `WhatsApp`, it will automatically move that folder. If you want to specify another directory, use `-m`.

> I think I was pointing to no Media folder actually, as I was running the cmd for the 2nd time. I was expecting the script to copy the files, not move them (although slower, it would be safer).
> 
> https://github.com/KnugiHK/Whatsapp-Chat-Exporter/blob/580eaddb24ee359433593776f1b6643e01d91979/Whatsapp_Chat_Exporter/extract.py#L531
> 
> Maybe it is worth an explicit warning that input files are being moved around?

We move the discussion of this to https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/25.

**Comment by KnugiHK** [comment] 2022-12-28 15:40
@velecto1
> I still have three issues, though:
> 
>     * All exported conversations start with "This message is not supported".
>     * The flag "-s" seems not to be working.
>     * I've realized that it would also be helpful for me to split the result into multiple HTML files see_no_evil.
Can you confirm if the first two issues happen only in the `message_table` branch? If they happen in the main branch, please open another issue for that.

**Comment by velecto1** [comment] 2023-01-05 05:53
> 

Hi, sorry for the delay; I didn't have the old backup available immediately.

1) Nope, the "This message is not supported" thing does not display in the resulting HTML when converting an old database. The chat is actually complete, so maybe it is the "message" saying: "Messages and calls are end-to-end encrypted..."

2) The 'main' branch doesn't have the '-s' flag available at all.

**Comment by KnugiHK** [comment] 2023-01-06 09:41
> > 
> 
> Hi, sorry for the delay; I didn't have the old backup available immediately.
> 
>     1. Nope, the "This message is not supported" thing does not display in the resulting HTML when converting an old database. The chat is actually complete, so maybe it is the "message" saying: "Messages and calls are end-to-end encrypted..."
> 
>     2. The 'main' branch doesn't have the '-s' flag available at all.

1. I will look into it.
2. Oh, yes. -s is not released yet.

**Comment by Ahmnonymous** [comment] 2023-02-04 18:44
> @velecto1
> 
> > I still have three issues, though:
> > ```
> > * All exported conversations start with "This message is not supported".
> > * The flag "-s" seems not to be working.
> > * I've realized that it would also be helpful for me to split the result into multiple HTML files see_no_evil.
> > ```
> 
> Can you confirm if the first two issues happen only in the `message_table` branch? If they happen in the main branch, please open another issue for that.

Hello there u can contact me I can help u out !

**Comment by KnugiHK** [comment] 2023-02-06 16:41
> > @velecto1
> > > I still have three issues, though:
> > > ```
> > > * All exported conversations start with "This message is not supported".
> > > * The flag "-s" seems not to be working.
> > > * I've realized that it would also be helpful for me to split the result into multiple HTML files see_no_evil.
> > > ```
> > 
> > 
> > Can you confirm if the first two issues happen only in the `message_table` branch? If they happen in the main branch, please open another issue for that.
> 
> Hello there u can contact me I can help u out but in private !

Feel free to poke me around in the Matrix network: https://matrix.to/#/!KtGjfSytJvzxewsXVd:matrix.org

**Comment by lordfeck** [comment] 2023-02-06 21:26
I've had the same problem. I was able to extract a Whatsapp DB from Android using the extractor tool and noticed it only has the 'message' table. Will give the test branch a try and see how it goes.

**Comment by KnugiHK** [comment] 2023-02-12 08:10
> I've had the same problem. I was able to extract a Whatsapp DB from Android using the extractor tool and noticed it only has the 'message' table. Will give the test branch a try and see how it goes.

This issue will likely happen to more and more people in the future as WhatsApp updates more people's database schema.

**Comment by flansch** [comment] 2023-02-12 13:47
I just used the code from the [message_table](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/tree/message_table) branch and was able to successfully export my Whatsapp database. I really appreciate your effort for this useful tool. The only thing I noticed in the resulting files is, that in group chats the name of the group is shown instead of the name of the person writing the message.

**Comment by KnugiHK** [comment] 2023-02-12 15:23
> I just used the code from the [message_table](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/tree/message_table) branch and was able to successfully export my Whatsapp database. I really appreciate your effort for this useful tool. The only thing I noticed in the resulting files is, that in group chats the name of the group is shown instead of the name of the person writing the message.

Thanks for reporting that, I can reproduce the problem.

**Comment by flansch** [comment] 2023-02-12 22:02
I updated to the latest version of the message_table branch and can confirm that the error is gone, thank you for that. In the meantime I had another issue: When opening the files in Safari on Mac the encoding is not detected properly and emojis and german umlauts are not displayed correctly. 
By adding `<meta charset="UTF-8">` to the head section of one of the files, I was able to fix that. Could you please automatically add this tag.

**Comment by KnugiHK** [comment] 2023-02-13 07:48
>
> 
> Hi, sorry for the delay; I didn't have the old backup available immediately.
> 
>     1. Nope, the "This message is not supported" thing does not display in the resulting HTML when converting an old database. The chat is actually complete, so maybe it is the "message" saying: "Messages and calls are end-to-end encrypted..."
> 
>     2. The 'main' branch doesn't have the '-s' flag available at all.

Metadata is also treated as message in the database, but since it is not the main focus when it comes to exporting chats, metadata may shows as "not supported" unless handled like changes of group name. Therefore, I will consider it not a bug if the chat is complete.

I will start preparing for the release when more tests are being performed.

**Comment by menotuu** [comment] 2023-02-28 11:44
hello, I have the "sqlite3.OperationalError: no such table: messages" error too.
But I am messing with the Whatsapp databases firstly around since today.
My used Whatsapp-Chat-Exporter version is: Minor Release 2023/01/31 0.85

and in this version it should be fixed right?

**Comment by lordfeck** [comment] 2023-03-01 20:30
I checked out the message_table branch and used it to extract my newer 'message' DB successfully. All conversations including group conversations were converted to HTML. Many thanks @KnugiHK !

**Comment by nahoj** [comment] 2023-03-17 10:45
I had to cherry-pick the fix for https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/32 and then it worked perfectly. Thank you for making this tool!

```bash
➜  Whatsapp-Chat-Exporter git:(message_table)$ git cherry-pick 2ba5571
➜  Whatsapp-Chat-Exporter git:(message_table)$ pip install '.[android_backup]'
```

**Comment by KnugiHK** [comment] 2023-03-25 04:02
Hello everyone! We are finally moving to the last step before releasing this update.

I merged the logic for processing old and new schema in `extract.py` in commit fb88124. As it is not a commit specifically for `message` table, it will not be merge into the `message_table` branch and the branch will not be updated from now on. And changes will be committed to `dev` branch as usual.

Feel free to give it a try, especially for those who have databases with both `message` and `messages` tables, to see if there is any compatibility issue.

**Comment by KnugiHK** [comment] 2023-04-08 17:45
> Hey there! Not sure if it's related, but I was having the same issue related to this thread, downloaded both the commit and the dev branch versions and now I'm getting a different error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/.local/bin/wtsexporter", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/user/.local/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 229, in main
>     messages(db, data)
>   File "/home/user/.local/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/extract.py", line 249, in messages
>     data[content["key_remote_jid"]].add_message(content["_id"], Message(
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'dict' object has no attribute 'add_message'
> ```
> 
> Again, not sure if it's related, but what should I do in this case, please?

What's the command you issued?

**Comment by KnugiHK** [comment] 2023-04-08 18:07
> Hiya there @KnugiHK, I ran `wtsexporter -a`. I have msgstore.db, wa.db and the WhatsApp folder (containing the Backups, Databases and Media folders) in the directory I tried to run the command.

@umjediqualquer I did a quick fix on it (b371587) in the dev branch. Would you please see if the fix works?

**Comment by KnugiHK** [comment] 2023-04-08 18:17
> > @umjediqualquer I did a quick fix on it ([b371587](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/commit/b371587d654714d18043a5cc1a46d949870232cb)) in the dev branch. Would you please check if the fix works?
> 
> Managed to make some progress, getting a different error message now:
> 
> ```
> Gathering messages...(694764/694764)
> Gathering media...(43618/43618)
> Traceback (most recent call last):
>   File "/home/user/.local/bin/wtsexporter", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/user/.local/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 231, in main
>     vcard(db, data)
>   File "/home/user/.local/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/extract.py", line 491, in vcard
>     file_name = "".join(x for x in media_name if x.isalnum())
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object is not iterable```
> ```

Do you know if your msgstore.db use `message` or `messages` table?

**Comment by KnugiHK** [comment] 2023-04-08 18:27
> > Do you know if your msgstore.db use `message` or `messages` table?
> 
> I'm assuming it's `message` because when running the release version, I get the `sqlite3.OperationalError: no such table: messages` error, but I can open this with a db viewer to double check.

Attempt on fixing it is pushed (06a1d34). See if that works (the error may disappear but it is not a good fix IMO).

**Comment by KnugiHK** [comment] 2023-04-08 18:43
> Is there a way to extract only the chat without the media?

There is no way to extract chat only. Maybe it is a good option to add.

> It's weekend and I don't to keep bothering you with this haha

That's fine. The bug has to be fixed anyway. And I only reply when I am available.

As for the bug, I committed another attempt to fix it. This time I modified my database to test the problem myself and it works for me. Also, maybe the file name should rely on the information inside the vcards instead of the message data (the current implementation).

**Comment by KnugiHK** [comment] 2023-04-09 09:15
> @KnugiHK it worked! Seems to have generated everything correctly and didn't throw any errors :D
> 
> Thank you very much for your help, especially on a weekend! May I buy you a cup of coffee (or tea, it that's your cup, heh) as a token of gratitude?

Glad that works for you too! And thanks for your report! The point for not releasing this update yet is to let everyone test it and spot problems.

Also, I appreciate your offer to buy me a cup of coffee or tea, but it's not necessary. If you'd like to show your support, consider staring this repo instead. That meant a lot to me😆. Thanks again.

**Comment by Signum21** [comment] 2023-04-17 22:53
Hi, I cloned the "message_table" branch and run the tool with this command:
python3 __main__.py -a --db ./msgstore.db

The messages are recovered correctly but i noticed that two identical "WhatsApp" folders are created.
One outside and one inside the "result" folder.
This might be a bug.

The two folders structure are:

./WhatsApp/
./WhatsApp/vCards/

./result/
./result/messages.html
./result/WhatsApp/
./result/WhatsApp/vCards/

**Comment by KnugiHK** [comment] 2023-04-18 14:32
Did "Copying media directory..." printed in your console? I guess your problem is related to [#25](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/25#issuecomment-1409962035).

Also, "message_table" branch is no longer maintained. Try dev branch instead.

**Comment by KnugiHK** [comment] 2023-04-25 05:07
The output treats deleted message as not supported message in the new schema. It is fixed in c7a01bb.

**Comment by UsamaAshfaq** [comment] 2023-05-08 10:51
> WhatsApp using "message" table spread different types of message to many other tables. Good chance for me to rewrite the project :)

Kindly do it, I am also getting same error : sqlite3.OperationalError: no such table: messages
In my case Messages are stored in "message" table.

**Comment by KnugiHK** [comment] 2023-05-08 17:54
> > WhatsApp using "message" table spread different types of message to many other tables. Good chance for me to rewrite the project :)
> 
> Kindly do it, I am also getting same error : sqlite3.OperationalError: no such table: messages In my case Messages are stored in "message" table.

The support of the `message` table is completed and will be released soon.

**Closed** 2023-05-16 13:00 UTC
Labels: enhancement, Priority
