### ISSUE TITLE
Provide reasons for "message not supported"

### ISSUE THREAD

**Issue by AlexanderRitter02** [KnugiHK/WhatsApp-Chat-Exporter#39] opened 2023-04-24 14:02 UTC
## Description
Hi,
WhatsApp meta messages like:
- `Chat is end-to-end encrypted`...
- `This message was deleted`

are currently treated as **"This message is not supported"**.

As noted in this comment, it's not a bug:
https://github.com/KnugiHK/Whatsapp-Chat-Exporter/issues/9#issuecomment-1427487785
> Metadata is also treated as messages in the database. But since it is not the main focus when it comes to exporting chats, metadata may show as "not supported" unless handled like changes of the group name. Therefore, I will consider it not a bug if the chat is complete.

This is mostly fine, but can cause concern among users thinking some messages are missing (and not everyone searches Github to find the issue).

## Suggestion
I suggest additionally providing the reason why the message is not supported (e.g. _deleted message_ or _whatsapp internal message_) instead of the generic comment that the message is not supported.  
This will make it clear that the message is not important.

It would be useful to alleviate the concerns of missing messages if looking through the backup at a later time.

You do detect that these messages are unsupported, so if individually detecting the type is infeasible, an option would also be to make the message less intimidating:
**`A Whatsapp internal message (phone changed, deleted messages, ...) is not supported`**

**Comment by KnugiHK** [comment] 2023-04-25 04:22
"This message was deleted" is supposed to be handled. At least it is handled before we move to the new schema. Therefore, it should be considered a bug. 

I agree we can add the reason why certain messages are not supported. On the other hand, we can also hide the metadata messages from the output. What do you think?

**Comment by KnugiHK** [comment] 2023-04-25 05:05
The missing of "Message deleted" should be fixed in c7a01bb.

**Comment by kintaro1981** [comment] 2023-06-10 12:39
I can confirm that "Message deleted" is fixed, I just tried with a iOS db.

How about supporting the other ones like, "<user> has left the group"?

I want to use Whatsapp-Chat-Exporter to archive many of my WA chats and free up space in the phone, but I would like in the future, for example, to know when a user left a group.

**Comment by KnugiHK** [comment] 2023-06-10 14:22
> I can confirm that "Message deleted" is fixed, I just tried with a iOS db.
> 
> How about supporting the other ones like, " has left the group"?
> 
> I want to use Whatsapp-Chat-Exporter to archive many of my WA chats and free up space in the phone, but I would like in the future, for example, to know when a user left a group.

More metadata will be supported in the future, I assume. But there is no timeline for their implementation.

**Comment by KnugiHK** [comment] 2023-06-15 17:48
> > I can confirm that "Message deleted" is fixed, I just tried with a iOS db.
> > How about supporting the other ones like, " has left the group"?
> > I want to use Whatsapp-Chat-Exporter to archive many of my WA chats and free up space in the phone, but I would like in the future, for example, to know when a user left a group.
> 
> More metadata will be supported in the future, I assume. But since parsing metadata requires understanding their binary representation, there is yet to be a timeline for their implementation.

FYI, 011c8ff implemented a metadata handling related to missed calls.

**Comment by KnugiHK** [comment] 2023-06-25 06:22
Released in 0.9.5.

**Closed by KnugiHK** 2023-06-25 06:22 UTC
Labels: bug, enhancement
