### ISSUE TITLE
iOS contact database not found - potential fix in description

### ISSUE THREAD

**Issue by achalddave** [KnugiHK/WhatsApp-Chat-Exporter#76] opened 2023-11-26 23:22 UTC
Thanks for this great tool! I received the following error when using this with the latest version of WhatsApp: "Contact database not found." I think the uuid(?) for the contacts db in whatsapp may have changed. 

Changing this line: https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/c27f5ee41cd97e5b954cff4dc4c08ba870be0fbf/Whatsapp_Chat_Exporter/utility.py#L299

from
```
    CONTACT = "b8548dc30aa1030df0ce18ef08b882cf7ab5212f"
```

to
```
    CONTACT = "016df2e52e5bfaa000f98a1dbe5c40cd6dc7f657"
```

fixed the issue for me. I'm not sure if this is a general fix, so I'm not submitting a PR, but opening this issue in case anyone else runs into it.

**Comment by KnugiHK** [comment] 2023-11-27 12:08
I currently don't have access to the latest iOS WhatsApp. Once it has been confirmed, I will make changes to the code. Thanks for your report and the potential fix anyway!

**Comment by SvenHerr** [comment] 2023-12-28 19:59
@achalddave how did you know that this is the new db ? i cant find 016df2e52e5bfaa000f98a1dbe5c40cd6dc7f657 with the version 17.2.1

**Comment by achalddave** [comment] 2024-01-01 23:41
I'm sure there's a better way, but I went to the path to my Manifest.db, which was in a path like: `~/Library/Application Support/MobileSync/Backup/<numbers>/Manifest.db`, and then ran:

```
~ sqlite3 Manifest.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> select * from files;
```

This printed a bunch of tables, and I looked for one which said `ContactsV2.sqlite`, and copied the hash at the start of that line.

**Comment by KnugiHK** [comment] 2024-01-02 13:02
> I'm sure there's a better way, but I went to the path to my Manifest.db, which was in a path like: `~/Library/Application Support/MobileSync/Backup/<numbers>/Manifest.db`, and then ran:
> 
> ```
> ~ sqlite3 Manifest.db
> SQLite version 3.39.5 2022-10-14 20:58:05
> Enter ".help" for usage hints.
> sqlite> select * from files;
> ```
> 
> This printed a bunch of tables, and I looked for one which said `ContactsV2.sqlite`, and copied the hash at the start of that line.

This is the correct way to find a file inside the iOS backup.

**Comment by SvenHerr** [comment] 2024-01-03 09:27
thank you for your reply. I just looked throu all files with .sqlite and i cant find any db with contacts.

**Comment by Rerebla** [comment] 2024-01-09 15:25
I get the same error "Contact database not found". Running the program with the default or the suggested fix results in the same error. I couldn't find any ContactsV2 or anything containing 'contacts' related to WhatsApp.

**Comment by roisec** [comment] 2024-02-27 20:48
@angelbanderasudg it's solved the issue but after I have another issue
Unexpected contact format: broadcast
```
  File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 425, in main
    create_html(
  File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/android_handler.py", line 753, in create_html
    safe_file_name, name = get_file_name(contact, chat)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/utility.py", line 141, in get_file_name
    raise ValueError("Unexpected contact format: " + contact)
ValueError: Unexpected contact format: broadcast
```

**Comment by jpfleischer** [comment] 2024-05-30 01:12
please merge @angelbanderasudg 's fix

**Comment by KnugiHK** [comment] 2024-06-30 10:09
> @angelbanderasudg it's solved the issue but after I have another issue Unexpected contact format: broadcast
> 
> ```
>   File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/__main__.py", line 425, in main
>     create_html(
>   File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/android_handler.py", line 753, in create_html
>     safe_file_name, name = get_file_name(contact, chat)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users//repos/iphone/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/utility.py", line 141, in get_file_name
>     raise ValueError("Unexpected contact format: " + contact)
> ValueError: Unexpected contact format: broadcast
> ```

I notice that your handler is for Android. Please open a separate issue for that as this issue exclusively appear in iOS.

**Comment by KnugiHK** [comment] 2024-07-20 05:58
A workaround has been implemented in #106.

**Comment by KnugiHK** [comment] 2024-09-07 13:48
Potential fix proposed in https://github.com/KnugiHK/WhatsApp-Chat-Exporter/issues/109#issuecomment-2267853193 by @ReclusiveEagle.

**Comment by KnugiHK** [comment] 2024-09-11 17:04
> I currently don't have access to the latest iOS WhatsApp. Once it has been confirmed, I will make changes to the code. Thanks for your report and the potential fix anyway!

I created an iOS (17.6.1) backup with WhatsApp 2.24.17.78. I do see the ContactsV2.sqlite file. Not sure how to reproduce the issue. Any ideas?

**Comment by KnugiHK** [comment] 2024-09-14 07:05
Hi @ReclusiveEagle, I took a look at your solution and it does not seem right to me.

> Using any of the unique hashes assigned to anyone of your contact's chat seem to fix the issue.
>
> For example:
>
>0618655a1de1254eca90c229002cdea325de408d for:
>```
>0618655a1de1254eca90c229002cdea325de408dAppDomainGroup-group.net.whatsapp.WhatsApp.sharedMessage/Media/[Contacts Number]@s.whatsapp.net/0/6/06693485-42bb-4f27-844d-1c37d93c1291.opusbplist00
>```
> In utility.py, for class WhatsAppIdentifier(StrEnum): replace the hash in CONTACT = "to the unique hash from one of your contacts." and run the script again.

However, the contact file should be a SQLite database, while your solution seems to be extracting a non-SQLite file—specifically, an audio file in this case.

**Comment by jpfleischer** [comment] 2024-09-14 07:08
for whatever reason, the hash from the audio file works. this has allowed me to use this library without throwing any errors

**Comment by KnugiHK** [comment] 2024-09-14 07:15
> for whatever reason, the hash from the audio file works. this has allowed me to use this library without throwing any errors

That might indeed help resolving the contact database not found error (I haven't test it), but it's not really a proper solution.

Instead, the contact database could treated as optional, if iOS backups can't guarantee its inclusion.

**Comment by KnugiHK** [comment] 2024-09-14 07:24
The commit fe88f1b should allow the tool to proceed even if the database is not presented.

**Comment by KnugiHK** [comment] 2024-10-24 11:49
The contact database may not be included in the iOS backup. Since there are no alternative files to replace it, the commit fe88f1b is deemed an appropriate solution. This fix was released in 0.10.5.

**Closed by KnugiHK** 2024-10-24 11:49 UTC
Labels: enhancement, ios
