### ISSUE TITLE
[FEATURE] Per Chat JSON Files

### ISSUE THREAD

**Issue by PrabhakarManara** [KnugiHK/WhatsApp-Chat-Exporter#86] opened 2024-02-23 07:34 UTC
**Is your feature request related to a problem? Please describe.**
I think a way to generate JSON code per contact will be very useful. With that others can make custom UI as they please.

**Describe the solution you'd like**
Json file which contains text messages and links to media wherever necessary

**Additional context**

**Comment by KnugiHK** [comment] 2024-02-23 12:24
Hi. Does adding the `--json` flag address what you want?

**Comment by PrabhakarManara** [comment] 2024-02-24 07:29
adding `--json` generates a JSON file containing chats of all contacts. when i tried, I got a 100mb json and cant open it and use it. I wish individual jsons are created like how individual htmls are created.

**Comment by KnugiHK** [comment] 2024-02-24 08:28
I see. I implemented it in 6e8e0d7. You can try that in the `dev` branch and with the `--json --per-chat` flags.

**Comment by code-consensus** [comment] 2024-09-03 12:14
Hi @KnugiHK ,

I noticed a bug here in _importing_ these per-chat json files.

Specifically, if one runs --json --per-chat, and say then you have a file "John_Doe.json".

If you then try to IMPORT that individual file with "wtsexporter --import --json John_Doe.json", you get an error in     import_from_json(args.json, data):
`chat = ChatStore(chat_data.get("type"), chat_data.get("name"))`
`AttributeError: 'str' object has no attribute 'get'"`

The problem is that the import_from_json() expects a _dictionary_ of ChatStore objects:
`{"15556665555@s.whatsapp.net": {{"name": "John Doe", "type": "android", .... }, "111@s.whatsapp.net": {...}...}`
whereas what is [_currently_ exported in main.py](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/__main__.py#L509) is _just_ the ChatStore object itself: 
`f.write(json.dumps(data[jik]))` results in:
{"name": "John Doe", "type": "android", .... }

**The solution** would be to export each chat as a _one-element_ dictionary of the ChatStore object. That is, change the code to:
`f.write(json.dumps({jik: data[jik]}))`

I have actually tested the above, and the generated per-chat json files can then be successfully re-imported without a problem.

**Comment by code-consensus** [comment] 2024-09-04 08:31
Hi @KnugiHK , there is another bug in the --per-chat implementation with regard to group chats. Specifically, **_if a group chat name has a special character_, the program will crash when writing the json file.**

e.g say a group chat has a name like "group-chat-name!?", then the python error traceback is as follows:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "..\wtsexporter.exe\__main__.py", line 7, in <module>
  File "...\Whatsapp_Chat_Exporter\__main__.py", line 508, in main
    with open(f"{args.json}/{contact}.json", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: "result/group-chat-name!?.json"

**Solution**
Name the json file with a "safe_file_name" the way [create_html() does on line 764](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/b34045a59fcd4da40c1021def34415039b789f8b/Whatsapp_Chat_Exporter/android_handler.py#L764).

**Comment by KnugiHK** [comment] 2024-09-07 10:48
> If you then try to IMPORT that individual file with "wtsexporter --import --json John_Doe.json", you get an error in import_from_json(args.json, data):
> ```
> chat = ChatStore(chat_data.get("type"), chat_data.get("name"))
> AttributeError: 'str' object has no attribute 'get'"
> ```

This should be fixed in fb5a1c3 according to your suggestion.

> there is another bug in the --per-chat implementation with regard to group chats. Specifically, if a group chat name has a special character, the program will crash when writing the json file.

This should be fixed in df3333f according to your suggestion.

Thanks for @code-consensus contribution!

**Closed** 2024-10-24 11:46 UTC
Labels: enhancement, pending for release
